version: '3.9'
services:
  app:
    build: .
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: dev
    expose:
      - '9000'
  web:
    image: nginx:1.25-alpine
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8000:80'
    depends_on:
      - app
