services:
  app:
    build:
      context: .
    environment:
      APP_ENV: prod
    volumes:
      - sqlite-data:/var/www/html/var
    expose:
      - "9000"

  cron:
    build:
      context: .
    command: >-
      sh -c "echo '0 0 * * * php /var/www/html/bin/console app:generate-notifications >> /proc/1/fd/1 2>&1' > /etc/crontabs/app && crond -f -L /proc/1/fd/1"
    volumes:
      - sqlite-data:/var/www/html/var
    depends_on:
      - app

  web:
    image: nginx:1.25-alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public:ro
    ports:
      - "8000:80"
    depends_on:
      - app

volumes:
  sqlite-data:
